name: Portfolio Project

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install NPM Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
      # - name: Upload artifact to deploy
      #   uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://soumen-k.github.io/portfolio-project/
    steps:
      - name: Deploy Artifact
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          name: production-files
          path: ./build
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

