name: Portfolio Project

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install NPM Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Upload artifact to deploy
        uses: actions/upload-artifact@v4
        with:
          name: production-files
        

